namespace Tekla.Introp.Contracts.Structures.Model.Enums
{
    public enum WeldElectrodeClassificationEnum
    {
        WELD_ELECTRODE_CLASSIFICATION_NONE,
        WELD_ELECTRODE_CLASSIFICATION_35,
        WELD_ELECTRODE_CLASSIFICATION_42,
        WELD_ELECTRODE_CLASSIFICATION_50,
        WELD_ELECTRODE_CLASSIFICATION_E60XX,
        WELD_ELECTRODE_CLASSIFICATION_E70XX,
        WELD_ELECTRODE_CLASSIFICATION_E80XX,
        WELD_ELECTRODE_CLASSIFICATION_E90XX
    }
}